version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test28093Project
  gitServerName: testEdgeProjects
  gitUrl: https://github.com/rlakshitha0912/Test28093Project
  gitUsername: rlakshitha0912
  gitToken: edge.scaffolding.Test28093Project.testEdgeProjects.gitToken
  gitBranch: main
